### ISSUE TITLE
Logic bug in eclipse-java init.sls

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/eclipse-formula#15]
When eclipse.user has value 'undefined_user' (possibly the default) the state ID 'eclipse-java-desktop-entry'  becomes undeclared in **init.sls**. 

```
     - require_in:
      - file: eclipse-java-desktop-entry
      - file: eclipse-java-remove-archive

{% if eclipse.user != 'undefined_user' %}

eclipse-java-desktop-entry:
```

The require/require_in statements need adjusting.
